
steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-f', 'trainer.dockerfile', '-t', 'gcr.io/dtumlops-375114/trainer', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/dtumlops-375114/trainer']
