steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-f', 'testing.dockerfile', '-t', 'gcr.io/dtumlops-375114/testing', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/dtumlops-375114/testing']
