steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-f', 'standardenvironment.dockerfile', '-t', 'gcr.io/vast-flight-374515/standardenvironment', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/vast-flight-374515/standardenvironment']
