wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1674124087.350964
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 5
bs:
  desc: null
  value: 16
e:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
o:
  desc: null
  value: Adam
pt:
  desc: null
  value: true
