name: "Run tests"

on:
  push:
    branches: [ master, main, testing ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
        matrix: 
          os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkouts
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install dvc 'dvc[gs]'
        dvc init --no-scm
        dvc remote add -d myremote gs://cats-and-dogs-dtumlops/
        dvc pull
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
